security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    foo: { password: test }
        user_db:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: user_db
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /

        default:
            anonymous: ~
